[package]
name = "novum"
version = "0.15.17"
edition = "2021"

[dependencies]
reedline = "0.50.0"
nu-ansi-term = "0.50.3"
csv = "1.4.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
rand = "0.10.2"

[lib]
name = "novum"
path = "src/lib.rs"

[[bin]]
name = "novum"
path = "src/main.rs"
